version: '3.8'
services:
  postgresql:
    image: postgres
    container_name: lessonrus
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_HOST=localhost
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=solver
      - POSTGRES_DATABASE=lessonrus
    command: postgres
    restart: always

  redis:
    image: redis:7.2.4-alpine
    container_name: redis-lessonrus
    ports:
      - '6379-6379'
